[tool.poetry]
name = "pyqt"
version = "0.1.0"
description = ""
authors = ["roman.zoria <zoryamba@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyqt6 = "^6.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
